version: "0.2"
files:
  - "**/*"
useGitignore: true
enableGlobDot: true
ignorePaths:
  - pnpm-lock.yaml
  - .git/
  - dist/
  - dev/cpp_vcpkg_project
  - "**/node_modules/"
  - .vscode/extensions.json
  - patches/*.patch
  - "**/github_*.json"
  - "**/llvm_org_releases.json"
words:
  - aarch
  - aminya
  - applellvm
  - armv
  - bazel
  - bazelisk
  - biome
  - biomejs
  - buildtools
  - caxa
  - ccache
  - choco
  - clangd
  - cmake
  - cobertura
  - copr
  - CPATH
  - Cppcheck
  - CPPFLAGS
  - cpprc
  - Cpython
  - DCMAKE
  - dearmor
  - deps
  - devel
  - dprint
  - DVCPKG
  - dyld
  - eabi
  - envosman
  - esmodule
  - execa
  - ftxui
  - GCOV
  - gcovr
  - ghes
  - Graphviz
  - hadolint
  - iarna
  - inja
  - isci
  - isroot
  - kcov
  - LDFLAGS
  - lefticus
  - libbinutils
  - libc
  - libdw
  - libstdc
  - libtinfo
  - liuli
  - memoizee
  - msbuild
  - msvc
  - msvcrt
  - msys
  - multilib
  - mxschmitt
  - nala
  - noconfirm
  - nodistro
  - NOPASSWD
  - noprogressbar
  - nothrow
  - npmrc
  - Opencppcoverage
  - OSSDK
  - papm
  - patha
  - pipx
  - pnpm
  - pnpx
  - pwsh
  - pygments
  - pypy
  - Sccache
  - setupcpp
  - setx
  - SYSROOT
  - Syuu
  - terserrc
  - Trofimovich
  - tsbuildinfo
  - ucrt
  - untildified
  - untildify
  - upleveled
  - vbatts
  - vcpkg
  - VCPKG
  - vcvarsall
  - venv
  - venvs
  - visualc
  - visualcpp
  - vsversion
  - whatwg
  - xcrun
  - Yahyaabadi
ignoreWords: []
import: []
dictionaryDefinitions: []
dictionaries: []
language: en, en-GB
allowCompoundWords: true
